"""Add preferred_room_class_id to Ward model, care_level and specialty to RoomClass model, and create WardRoomClassAssignment model

Revision ID: 5c8e5e0240d6
Revises: 0f5a3b93e180
Create Date: 2025-08-05 16:42:35.984584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c8e5e0240d6'
down_revision = '0f5a3b93e180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward_room_class_assignment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ward_id', sa.String(length=36), nullable=False),
    sa.Column('room_class_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('min_capacity', sa.Integer(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['room_class_id'], ['room_class.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('care_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('specialty', sa.String(length=100), nullable=True))

    with op.batch_alter_table('ward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_room_class_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'room_class', ['preferred_room_class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('preferred_room_class_id')

    with op.batch_alter_table('room_class', schema=None) as batch_op:
        batch_op.drop_column('specialty')
        batch_op.drop_column('care_level')

    op.drop_table('ward_room_class_assignment')
    # ### end Alembic commands ###
