"""Payor information

Revision ID: 691a2e0fbd3e
Revises: 841a5adb64eb
Create Date: 2025-08-15 07:37:40.211161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691a2e0fbd3e'
down_revision = '841a5adb64eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payor_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payor_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('payor_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payor_type_id'], ['payor_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payor_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payor_detail', sa.String(length=100), nullable=True))
        batch_op.drop_column('insurance_provider')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('payor_detail')
        batch_op.drop_column('payor_type')

    op.drop_table('payor_details')
    op.drop_table('payor_types')
    # ### end Alembic commands ###
