"""Add new fields to patient table

Revision ID: 90d1c99c0a9e
Revises: d96b1dcf5f54
Create Date: 2025-08-08 12:45:52.129311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d1c99c0a9e'
down_revision = 'd96b1dcf5f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_provider', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_deceased', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('is_deceased')
        batch_op.drop_column('insurance_provider')

    # ### end Alembic commands ###
