"""Add dynamic fields to patient table

Revision ID: abc123
Revises: 
Create Date: 2025-08-08

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc123'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('problematic_patient_reason', sa.Text(), nullable=True))
    op.add_column('patient', sa.Column('loyalty_member_number', sa.String(length=50), nullable=True))
    op.add_column('patient', sa.Column('chronic_condition_details', sa.Text(), nullable=True))
    op.add_column('patient', sa.Column('allergy_alert_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'allergy_alert_details')
    op.drop_column('patient', 'chronic_condition_details')
    op.drop_column('patient', 'loyalty_member_number')
    op.drop_column('patient', 'problematic_patient_reason')
    # ### end Alembic commands ###