"""empty message

Revision ID: d96b1dcf5f54
Revises: 
Create Date: 2025-08-06 18:37:57.583501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96b1dcf5f54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationality',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('id_card_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('blood_type', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('birthplace', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('marriage_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nationality_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('vip_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('problematic_patient', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('loyalty_member', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ihs_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('chronic_condition', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allergy_alert', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('preferred_communication', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'nationality', ['nationality_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('preferred_communication')
        batch_op.drop_column('allergy_alert')
        batch_op.drop_column('chronic_condition')
        batch_op.drop_column('ihs_number')
        batch_op.drop_column('loyalty_member')
        batch_op.drop_column('problematic_patient')
        batch_op.drop_column('vip_status')
        batch_op.drop_column('nationality_id')
        batch_op.drop_column('marriage_status')
        batch_op.drop_column('birthplace')
        batch_op.drop_column('blood_type')
        batch_op.drop_column('id_card_number')
        batch_op.drop_column('id_type')

    op.drop_table('nationality')
    # ### end Alembic commands ###
